services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "${PORT:-7777}:${PORT:-7777}"
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=mysql://root:ckcfit@mysql:3306/homeconnectiot
      - AIVEN_URL=${AIVEN_URL}
      - APP_SECRET=${APP_SECRET}
      - PORT=${PORT:-7777}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - NODE_ENV=${NODE_ENV:-development}
    depends_on:
      - mysql
      - redis
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "3350:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ckcfit
      - MYSQL_DATABASE=homeconnectiot
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:alpine
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:
